apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-resources-role
rules:
- apiGroups:
  - otus.homework
  resources:
  - mysqls
  verbs:
  - get
  - list
  - patch
  - watch
  - create
  - delete
- apiGroups:
  - "*"
  resources:
  - services
  - persistentvolumes
  - persistentvolumeclaims
  - deployments
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - delete