apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: app
  annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app"
        vault.hashicorp.com/service: "http://vault-server.vault:8200"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/secret-volume-path: '/app/configs'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/apps/service" -}}
          test-cfg://{{ .Data.data.creds }}
          {{- end }} 
spec:
  serviceAccountName: vault-auth
  containers:
    - name: nginx-container
      image: nginx


---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: app
  name: vault-auth
  labels:
    app: vault_auth_agent