apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: grafana
    version: 6.40.5
    repository: https://grafana.github.io/helm-charts
    alias: grafana
    condition: grafana.enabled