apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: homework
  labels:
     app: monitoring
spec:
  selector:
    matchLabels:
       app: nginx
  endpoints:
    - interval: 10s 
      port: metrics