apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-templationg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL: "https://github.com/Kuber-2024-02OTUS/siestacloud.git"
    path: kubernetes-templating/template-chart-sps
    targetRevision: HEAD
    helm:
      values: |
    deploy:
      replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true