apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        homework: "true"
      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: nginx-default-config-volume
        configMap:
          name: nginx-default-config-homework
      terminationGracePeriodSeconds: 4
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'wget -O /init/index.html https://www.w3.org/Style/CSS/Test/CSS3/Selectors/current/html/tests/css3-modsel-1.html']
        volumeMounts:
          - mountPath: /init
            name: shared-volume
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
        - name: NGINX_PORT
          value: "8000"
        volumeMounts:
          - mountPath: /homework
            name: shared-volume
          - name: nginx-default-config-volume
            mountPath: /etc/nginx/conf.d/
        ports:
          - containerPort: 8000
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -f /homework"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-config-homework
data:
  default.conf: |
    server {
        listen 8000;
        server_name _;
        location / {
            try_files $uri $uri/ /index.html;
            root /homework;
            index  index.html index.htm;
        }
    }
