{{- if .Values.serviceAccountMonitoring.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template-chart-sps.fullname" . }}-cr
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
{{- end }}