{{- if .Values.serviceAccountMonitoring.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template-chart-sps.fullname" . }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ include "template-chart-sps.fullname" . }}-monitoring
    namespace: homework
roleRef:
  kind: ClusterRole
  name: {{ include "template-chart-sps.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}