{{- if .Values.pvc.create -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.pvc.storageClassName }}
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: network-hdd
provisioner: disk-csi-driver.mks.ycloud.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- end }}