---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
  namespace: homework
spec:
  storageClassName: yc-network-hdd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi